### ISSUE TITLE
裁剪原图，图片过大，无法有效地剪裁缩小后的图片

### ISSUE THREAD

**Issue by Roqii** [acccccccb/vue-img-cutter#49]
**bug描述**
设置：originalGraph: true  //	是否直接裁剪原图   
操作：上传4K图片，滚动缩小图片发现像素框并非固定值(像素异常变大)。
![image](https://user-images.githubusercontent.com/5799590/133717153-709139bd-239f-4a89-bef2-b71003952919.png)

**版本号**
2.2.5
**浏览器版本**
Chrome

**Comment by acccccccb** [comment]
这个像素框对应的是原图 根据当前图片缩放比例和像素框计算出来的

**Comment by Roqii** [comment]
情景：我要上传一张很大很漂亮的图，但我只要等比例缩放之后截取300x300像素，这个像素框我希望是包含缩小后图片的内容。
问题：如果是等比例缩放（不改图片像素，只作剪裁）就不能满足固定像素设立。
建议：多一个选项，缩放图片进行剪裁。这样这个项目就多了一个压缩功能了

**Comment by acccccccb** [comment]
将裁剪原图的属性设置为 false
&nbsp;

&#160;
 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 中午11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [acccccccb/vue-img-cutter] 裁剪原图，图片过大，无法有效地剪裁缩小后的图片 (#49)





 
情景：我要上传一张很大很漂亮的图，但我只要等比例缩放之后截取300x300像素，这个像素框我希望是包含缩小后图片的内容。
 问题：如果是等比例缩放（不改图片像素，只作剪裁）就不能满足固定像素设立。
 建议：多一个选项，缩放图片进行剪裁。这样这个项目就多了一个压缩功能了
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
